# Generated by Django 3.2.3 on 2021-05-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsmodels',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
