# Generated by Django 3.2.3 on 2021-05-24 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Clients', '0002_alter_clientsmodels_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=120, null=True)),
                ('Qualification', models.CharField(blank=True, max_length=120, null=True)),
                ('fromeducation', models.CharField(blank=True, max_length=120, null=True)),
                ('university_education', models.CharField(blank=True, max_length=120, null=True)),
                ('toeducation', models.CharField(blank=True, max_length=120, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
