# Generated by Django 3.2.3 on 2021-05-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0003_qualificationmodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualificationmodels',
            name='user',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
