# Generated by Django 3.2.3 on 2021-05-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0004_alter_qualificationmodels_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=120, null=True)),
                ('company', models.CharField(blank=True, max_length=120, null=True)),
                ('skill', models.CharField(blank=True, max_length=120, null=True)),
                ('fromskill', models.CharField(blank=True, max_length=120, null=True)),
                ('toskill', models.CharField(blank=True, max_length=120, null=True)),
                ('company_attended', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
