# Generated by Django 3.2.3 on 2021-05-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0005_skillsmodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=120, null=True)),
                ('company', models.CharField(blank=True, max_length=120, null=True)),
                ('skillsexperience', models.CharField(blank=True, max_length=120, null=True)),
                ('Levelexperience', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
