# Generated by Django 3.2.3 on 2021-05-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0006_experiencemodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateaded', models.CharField(blank=True, max_length=120, null=True)),
                ('user', models.CharField(max_length=120, null=True)),
                ('company', models.CharField(blank=True, max_length=120, null=True)),
                ('fullname', models.CharField(blank=True, max_length=120, null=True)),
                ('cvtittle', models.CharField(blank=True, max_length=120, null=True)),
                ('cvfile', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
