# Generated by Django 3.2.3 on 2021-05-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0007_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='status',
            field=models.CharField(blank=True, default='Active', max_length=120),
        ),
    ]
