# Generated by Django 3.2.3 on 2021-05-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0008_alter_cv_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateaded', models.CharField(blank=True, max_length=120, null=True)),
                ('user', models.CharField(max_length=120, null=True)),
                ('package', models.CharField(blank=True, max_length=120, null=True)),
                ('company', models.CharField(blank=True, max_length=120, null=True)),
                ('fullname', models.CharField(blank=True, max_length=120, null=True)),
                ('timeframe', models.CharField(blank=True, max_length=120, null=True)),
                ('percentage', models.FileField(blank=True, null=True, upload_to='')),
                ('Description', models.CharField(blank=True, default='Active', max_length=120)),
                ('status', models.CharField(blank=True, default='Active', max_length=120)),
            ],
        ),
    ]
