# Generated by Django 3.2.3 on 2021-05-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0011_job_posts_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_applied', models.CharField(blank=True, max_length=120, null=True)),
                ('Job_title', models.CharField(blank=True, max_length=120, null=True)),
                ('applicant_username', models.CharField(blank=True, max_length=120, null=True)),
                ('name_of_applicant', models.CharField(blank=True, max_length=120, null=True)),
                ('Age_of_applicant', models.CharField(blank=True, max_length=120, null=True)),
                ('company', models.CharField(blank=True, max_length=120, null=True)),
                ('category', models.CharField(blank=True, max_length=120, null=True)),
                ('officer_posted', models.CharField(blank=True, max_length=120, null=True)),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.CharField(blank=True, max_length=120, null=True)),
                ('start', models.CharField(blank=True, max_length=120, null=True)),
                ('end', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
