# Generated by Django 3.2.3 on 2021-05-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0012_applied'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_deleted', models.CharField(blank=True, max_length=120, null=True)),
                ('Section', models.CharField(blank=True, max_length=120, null=True)),
                ('Person_deleted', models.CharField(blank=True, max_length=120, null=True)),
                ('Heading_thread', models.CharField(blank=True, max_length=120, null=True)),
                ('company', models.CharField(blank=True, max_length=120, null=True)),
                ('officer', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
