# Generated by Django 3.2.3 on 2021-06-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0013_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsmodels',
            name='Country',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
