# Generated by Django 3.2.3 on 2021-06-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0015_clientsmodels_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_posts',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='job_posts',
            name='working_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
