# Generated by Django 3.2.3 on 2021-06-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0016_auto_20210616_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_posts',
            name='Short_description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
