# Generated by Django 3.2.3 on 2021-06-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0018_auto_20210617_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsmodels',
            name='company',
            field=models.CharField(blank=True, default='self', max_length=120),
        ),
    ]
