# Generated by Django 3.2.3 on 2021-06-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0019_clientsmodels_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_posts',
            name='experience',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='job_posts',
            name='workexperience',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
