# Generated by Django 3.2.3 on 2021-06-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0020_auto_20210620_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_posts',
            name='Gender',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='job_posts',
            name='language',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
