# Generated by Django 3.2.3 on 2021-06-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0022_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsmodels',
            name='company_profile',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
