# Generated by Django 3.2.3 on 2021-06-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0024_applied_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied',
            name='Gender',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='applied',
            name='Qualification',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='applied',
            name='experience',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='applied',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='applied',
            name='workexperience',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
