# Generated by Django 3.2.3 on 2021-06-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0025_auto_20210624_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.CharField(blank=True, max_length=120, null=True)),
                ('username', models.CharField(blank=True, max_length=120, null=True)),
                ('company_name', models.CharField(blank=True, max_length=120, null=True)),
                ('officer_name', models.CharField(blank=True, max_length=120, null=True)),
                ('possition', models.CharField(blank=True, max_length=120, null=True)),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='')),
                ('bio', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.CharField(blank=True, max_length=120, null=True)),
                ('company_name', models.CharField(blank=True, max_length=120, null=True)),
                ('officer_added', models.CharField(blank=True, max_length=120, null=True)),
                ('profile_photo', models.CharField(blank=True, max_length=120, null=True)),
                ('bio', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
