# Generated by Django 3.2.3 on 2021-06-28 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0027_auto_20210625_1304'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='company_name',
        ),
    ]
