# Generated by Django 3.2.3 on 2021-06-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0028_alter_company_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table=None,
        ),
    ]
