# Generated by Django 3.2.3 on 2021-07-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0029_alter_company_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientsmodels',
            old_name='Country',
            new_name='Counto',
        ),
    ]
