# Generated by Django 3.2.3 on 2021-07-02 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0030_rename_country_clientsmodels_counto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientsmodels',
            old_name='Counto',
            new_name='Country',
        ),
    ]
