# Generated by Django 3.2.3 on 2021-07-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0031_rename_counto_clientsmodels_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_token', models.DateTimeField(auto_now=True, null=True)),
                ('username', models.CharField(blank=True, max_length=120, null=True)),
                ('company_name', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
