# Generated by Django 3.2.3 on 2021-07-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0032_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='voucher_token',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
