# Generated by Django 3.2.3 on 2021-07-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0033_alter_voucher_voucher_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='voucher_token',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
