# Generated by Django 3.2.3 on 2021-07-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0034_alter_voucher_voucher_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('used', 'used')], max_length=120, null=True),
        ),
    ]
