# Generated by Django 3.2.3 on 2021-07-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0035_voucher_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='voucher',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
