# Generated by Django 3.2.3 on 2021-07-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0036_voucher_voucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='voucher',
        ),
    ]
