# Generated by Django 3.2.3 on 2021-08-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0038_auto_20210806_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsmodels',
            name='company_profile',
            field=models.CharField(blank=True, max_length=920, null=True),
        ),
        migrations.AlterField(
            model_name='clientsmodels',
            name='description',
            field=models.CharField(blank=True, max_length=920, null=True),
        ),
    ]
