# Generated by Django 3.2.3 on 2021-09-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0040_auto_20210810_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsmodels',
            name='token',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
