# Generated by Django 3.2.3 on 2021-09-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0042_emails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emails',
            old_name='title',
            new_name='content',
        ),
        migrations.AddField(
            model_name='emails',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
