# Generated by Django 3.2.3 on 2021-09-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0043_auto_20210911_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='date',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
