# Generated by Django 3.2.3 on 2021-09-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0046_experiencemodels_company_attended'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client_profile',
            options={'verbose_name_plural': 'Candidate profiles'},
        ),
        migrations.AddField(
            model_name='experiencemodels',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='skillsmodels',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client_profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job_posts',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job_posts',
            name='workexperience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
