# Generated by Django 3.2.3 on 2021-09-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0047_auto_20210914_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied',
            name='workexperience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
