# Generated by Django 3.2.3 on 2021-09-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0048_alter_applied_workexperience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientsmodels',
            options={'verbose_name_plural': 'List of clients & Candidates'},
        ),
        migrations.AlterModelOptions(
            name='experiencemodels',
            options={'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='skillsmodels',
            options={'verbose_name_plural': 'Experience'},
        ),
        migrations.AddField(
            model_name='skillsmodels',
            name='role',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
